#!/bin/sh
alias cd='z'
alias f='zi'
alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'
alias ls="exa --icons --color=always"
alias tree='exa -T --git-ignore -I "**/node_modules" --icons --group-directories-first'
alias weather='curl wttr.in\?format="%l:+%c+%t+feels+like+%f\n"'
alias cat="bat --style=auto"
alias bu="bundle update"
alias bi="bundle install"
alias rsp="rspec"
alias rt="rails test:all"
alias gph="git push heroku main"
alias h="heroku"
alias dbmigrate="rails db:migrate"
alias dbcreate="rails db:create"
alias dbdrop="rails db:drop"
alias dbrollback="rails db:rollback"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# systemd
alias mach_list_systemctl="systemctl list-unit-files --state=enabled"
